### ISSUE TITLE
No games found

### ISSUE THREAD

**Issue by seriema** [thadmiller/ES-scraper#12]
I've tried this in several ways and I thought it was working for a moment but now I'm not sure. If I run this to rescrape C64:

```
python scraper.py -pisize -name c64 -platform c64 -f -l
```

I get:

```
ES-scraper, a scraper for EmulationStation
Using Raspberry Pi boxart size: (375px x 350px)
Re-scraping all games..
Scanning folder..(/home/pi/RetroPie/roms/c64)

Trying to identify xyz.t64..

[etc for every file in the folder]

No new games added.
All done!
```

**Comment by seriema** [comment]
Seems like @Pompitousofseth found the same thing after closing #10

**Comment by Pompitousofseth** [comment]
It finds my games fine. Just when it's scraping them it can't find them in the database. I get this after typing "python scraper.py -pisize -pi:

Trying to identify Casino Kid 2 (U) [!].nes..
- No options found.
  Enter 'r' to search alternate title, 'a' to search all platforms, or
  press Enter to skip):
  Skipping game...

Trying to identify Darkwing Duck (U) [!].nes..
- No options found.
  Enter 'r' to search alternate title, 'a' to search all platforms, or
  press Enter to skip):
  Skipping game...

Trying to identify Days of Thunder (U) [!].nes..
- No options found.
  Enter 'r' to search alternate title, 'a' to search all platforms, or
  press Enter to skip):

**Comment by seriema** [comment]
If I revert the #9 PR (https://github.com/thadmiller/ES-scraper/commit/6ace5161336c6f3208d0ff87ef08e5918fe4ea0e) then it seems to be working again. Can you check what it was meant to fix actually? Because the change was ignoring the `_platforms` passed into the function and relying on the global `ES_systems`. The description on the commit says it was fixing a major issue when not using the `-p` flag, but I'm running without that flag and it seems to be fine.

**Comment by seriema** [comment]
@Pompitousofseth if you run with the `-l` "feeling lucky flag" then it won't ask and your output should match mine.

**Comment by Pompitousofseth** [comment]
I tried the -l flag and got: 

Trying to identify Yo! Noid (U) [!].nes..

Trying to identify Yoshi's Cookie.nes..

Trying to identify Zelda II - Adventure of Link.nes..
No new games added.
Scanning folder..(/home/pi/RetroPie/roms/ports)

Trying to identify Doom 1 Shareware.sh..

Trying to identify Duke3D Shareware.sh..

Trying to identify Kodi.sh..
No new games added.
Scanning folder..(/media/usb/psx)
No new games added.
Scanning folder..(/home/pi/RetroPie/roms/snes)

Trying to identify F-Zero.smc..

Trying to identify N.B.A. Jam.smc..
No new games added.
All done!
pi@retropie ~/ES-scraper $

**Comment by seriema** [comment]
@Pompitousofseth yeah I'd say that matches my output, wouldn't you say? The issue is the faulty PR #9 that caused the extra `)` you found. You can manually revert it locally or check out my PR #13

**Comment by Pompitousofseth** [comment]
How do I get pull the code? I'm not that great with the Linux codes ect. I understand some basics but it's getting a little to advanced for me. Sorry

**Comment by seriema** [comment]
@Pompitousofseth Maybe you can just manually change your local file like you did last time? Here's the diff: https://github.com/thadmiller/ES-scraper/pull/13/files
Let me know if it works.
