### ISSUE TITLE
TypeError: list indices must be integers, not tuple

### ISSUE THREAD

**Issue by Lotharyx** [thadmiller/ES-scraper#16]
I am sorry that I don't know Python at all to try to help debug this.  Here's a bash transcript of what happens on my system (Pi 2 B, Raspbian Jessie, ES fully updated):

```
pi@raspberrypi:~/git/ES-scraper $ python scraper.py -pisize -l
ES-scraper, a scraper for EmulationStation
Using Raspberry Pi boxart size: (375px x 350px)
I'm feeling lucky enabled. Minimum score of 1.
Scanning all systems.
Traceback (most recent call last):
  File "scraper.py", line 708, in <module>
    scanFiles(ES_systems[v])
TypeError: list indices must be integers, not tuple
```

Let me know what additional information I can provide that will be helpful.

**Comment by daande** [comment]
I am also receiving this error on RetroPie 3.5.  Also does it matter where in the filesystem /ES-Scraper/ is located?

**Comment by artem-schander** [comment]
+1 investing

**Comment by jimkill** [comment]
Im getting this error as well, has anyone gotten it to work on RetroPie 3.6?

**Comment by rajachan** [comment]
For those of you having this issue, commit abcc31f fixes it. This ticket should be closed.
