### ISSUE TITLE
GetGamesList.php by platform does not return full list of games to scrub

### ISSUE THREAD

**Issue by Naomarius** [thadmiller/ES-scraper#18]
You can get a full list using the -accurate arg but the regular method doesn't return a full comprehensive list.

I've rewrote some of the code to use the new GetPlatformGames.php I noticed the GetGamesList.php when passing Nintendo 64 was not returning a full list of games, omitting a good amount.

I'd like to contribute my changes so the regular parser will parse the full list of games for each platform using the platforms id.

Old url: http://thegamesdb.net/api/GetGamesList.php?platform=nintendo%2064
New url: http://thegamesdb.net/api/GetPlatformGames.php?platform=3

**Comment by thadmiller** [comment]
I've noticed the same thing, thegamesdb must have changed the original functionality (it was pulling the full list when originally created).  If you have already made the updates to the code, do a pull request and I'll update the master branch.  Thanks.

**Comment by Naomarius** [comment]
Sure thing I'll put one in tomorrow.
